spring:
  data:
    mongodb:
      uri: mongodb+srv://admin:1234@movie-book.kyjbafy.mongodb.net/?retryWrites=true&w=majority&serverSelectionTimeoutMS=5000&connectTimeoutMS=5000
      database: movie-book